#!/bin/sh

[ -r conf ] && . ./conf

if [ -x /sbin/getty -o -x /bin/getty ]; then
	# busybox
	GETTY=getty
elif [ -x /sbin/agetty -o -x /bin/agetty ]; then
	# util-linux
	GETTY=agetty
fi

exec setsid ${GETTY} ${GETTY_ARGS} -nl $PREFIX_DIRECTORY/bin/$EXECUTABLE_NAME "${TTY}" "${BAUD_RATE}" "${TERM_NAME}"
