const build_options = @import("build_options");
const enums = @import("../enums.zig");

const Animation = enums.Animation;
const Input = enums.Input;

const Config = @This();

ly: struct {
    animation: Animation,
    asterisk: u8,
    bg: u8,
    bigclock: bool,
    blank_box: bool,
    blank_password: bool,
    clock: []const u8,
    console_dev: []const u8,
    default_input: Input,
    fg: u8,
    hide_borders: bool,
    hide_key_hints: bool,
    input_len: u8,
    lang: []const u8,
    load: bool,
    margin_box_h: u8,
    margin_box_v: u8,
    max_desktop_len: u8,
    max_login_len: u8,
    max_password_len: u8,
    mcookie_cmd: []const u8,
    min_refresh_delta: u16,
    path: []const u8,
    restart_cmd: []const u8,
    restart_key: []const u8,
    save: bool,
    save_file: []const u8,
    service_name: []const u8,
    shutdown_cmd: []const u8,
    shutdown_key: []const u8,
    term_reset_cmd: []const u8,
    term_restore_cursor_cmd: []const u8,
    tty: u8,
    wayland_cmd: []const u8,
    wayland_specifier: bool,
    waylandsessions: []const u8,
    x_cmd: []const u8,
    xinitrc: []const u8,
    x_cmd_setup: []const u8,
    xauth_cmd: []const u8,
    xsessions: []const u8,
},

pub fn init() Config {
    return .{ .ly = .{
        .animation = .none,
        .asterisk = '*',
        .bg = 0,
        .bigclock = false,
        .blank_box = true,
        .blank_password = false,
        .clock = "",
        .console_dev = "/dev/console",
        .default_input = .login,
        .fg = 9,
        .hide_borders = false,
        .hide_key_hints = false,
        .input_len = 34,
        .lang = "en",
        .load = true,
        .margin_box_h = 2,
        .margin_box_v = 1,
        .max_desktop_len = 100,
        .max_login_len = 255,
        .max_password_len = 255,
        .mcookie_cmd = "/usr/bin/mcookie",
        .min_refresh_delta = 5,
        .path = "/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin",
        .restart_cmd = "/sbin/shutdown -r now",
        .restart_key = "F2",
        .save = true,
        .save_file = "/etc/ly/save",
        .service_name = "ly",
        .shutdown_cmd = "/sbin/shutdown -a now",
        .shutdown_key = "F1",
        .term_reset_cmd = "/usr/bin/tput reset",
        .term_restore_cursor_cmd = "/usr/bin/tput cnorm",
        .tty = 2,
        .wayland_cmd = build_options.data_directory ++ "/wsetup.sh",
        .wayland_specifier = false,
        .waylandsessions = "/usr/share/wayland-sessions",
        .x_cmd = "/usr/bin/X",
        .xinitrc = "~/.xinitrc",
        .x_cmd_setup = build_options.data_directory ++ "/xsetup.sh",
        .xauth_cmd = "/usr/bin/xauth",
        .xsessions = "/usr/share/xsessions",
    } };
}
